### ISSUE TITLE
npm install?

### ISSUE THREAD

**Issue by sdebaun** [firebase/firebase-util#19]
Per #6:

  npm install firebase/firebase-util -S

Is not working for me.  The node_modules/firebase-util directory that gets created has /src, /test/ and /node_modules but no /dist.  The firebase-util/package.json specifies its main as dist/firebase-util.min.js, which does not exist.

I have not tried the bower install suggested in #6, but I'm hoping to use firebase-util on both server and client.

**Comment by katowulf** [comment]
@jwngr is this a catapult issue?

**Comment by jwngr** [comment]
@katowulf - As far as I can tell, this has never been released through Catapult... Unfortunately the Jenkins logs don't go back to December 16th (when it was last tagged), but it looks like [you did that tag](https://github.com/firebase/firebase-util/releases/tag/v0.1.0). If it went through Catapult, it would have been tagged by @firebase-ops. There are also no commits from @firebase-ops which get created during the deploy process. Also, no Tweet from @FirebaseStatus on Twitter.

So it looks like you just manually do this tag instead of using Catapult. In that case, I'm not surprised the `/dist` directory is not there. I also wouldn't expect Bower to work either. We should do a new release to fix this.

**Comment by katowulf** [comment]
I think we'll just push it tomorrow/wed when I do the 0.2 release then. Until then, the workaround would be to `npm install` and then run `gulp` to build the dist/ folder.

**Comment by katowulf** [comment]
Yeah, actually, it looks like we never released this to npm.  So the current behavior looks correct, until we release via npm.

**Comment by jwngr** [comment]
Oh, right. That'll do it. It certainly is not on npm yet. When we release it later this week, it will be though.

@sdebaun - The way we set up our repos prevents people from doing what you attempted to do (aka npm installing from a GitHub repo), but that is by design. We only want people using versions of our libraries that have actually been tagged for production use. npm installing the master branch of a repo is generally bad practice and can lead to headaches for us and for you.

**Comment by sdebaun** [comment]
0.2 coming out?  yay!

will i be able to bower install then?

**Comment by jwngr** [comment]
Yup, it'll be available from both bower and npm.

**Comment by sdebaun** [comment]
awesome, thank you so much both of you!
