### ISSUE TITLE
on('child_changed',...) is being called many times when remove/re-add a record key

### ISSUE THREAD

**Issue by AaronJPA** [firebase/firebase-util#36]
`on('child_changed',...)` is being called many times when it probably shouldn't.

I'm opening four different issues because I'm not sure if they are related and, if they are not, they can be fixed separately. However, I used the same Plunker to simulate all of them, so it is a little bigger than usual. I tried to explain everything in the comments, but if something is not clear enough, just let me know.

http://plnkr.co/edit/Y0mp2XDtSQ0Pz9ClXctZ

**Comment by katowulf** [comment]
Thanks for the report. Essentially, the only difference I see between this and the current SDK behavior is that the child_changed event is triggered once for each merged path in some cases. It fires fairly consistently with the API in other regards (e.g. deleting an item in Firebase triggers a child_changed with a null value).

I don't see any great way to improve on the `child_changed` calls within the current limitations of the API. Essentially, since changing or deleting a record requires iterating the merged nodes and applying the change to each, and since there is no atomic way to do this in Firebase, we'll get the locally triggered events individually.

I looked at some options for trying to debounce the calls and wait for all the merged nodes to update before triggering, but timing of updates and ordering of records quickly grew too complex to predict. 

I did make a couple adjustments that will help. One was to ensure that records will not trigger `value` events if the value hasn't changed since the last event. That should cut down the frequency of the messages a bit. I'll check that in shortly.

**Comment by katowulf** [comment]
Found some more clues while working on the [filter/value issue](https://github.com/firebase/firebase-util/issues/35). So this appears to be an issue with listeners getting attached multiple times. After records are deleted, the event listeners are not properly being removed. However, after the record is recreated, it triggers child_changed events twice.
